package simpledb;
import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends AbstractDbIterator {

    /**
     * Constructor.  Accepts to children to join and the predicate
     * to join them on
     *
     * @param p The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    private DbIterator child1, child2;
    private Tuple t1 = null;
    private JoinPredicate jp;
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        jp = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    /**
     * @see simpledb.TupleDesc#combine(TupleDesc, TupleDesc) for possible implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return TupleDesc.combine(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open()
        throws DbException, NoSuchElementException, TransactionAbortedException {
        child1.open();
        child2.open();
    }

    public void close() {
        child1.close();
        child2.close();
        t1 = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
        t1 = null;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no more tuples.
     * Logically, this is the next tuple in r1 cross r2 that satisfies the join
     * predicate.  There are many possible implementations; the simplest is a
     * nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of
     * Join are simply the concatenation of joining tuples from the left and
     * right relation. Therefore, if an equality predicate is used 
     * there will be two copies of the join attribute
     * in the results.  (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    private static Tuple join(Tuple t1, Tuple t2) {
        TupleDesc tdr = TupleDesc.combine(t1.getTupleDesc(), t2.getTupleDesc());
        Tuple r = new Tuple(tdr);
        int len1 = t1.getTupleDesc().numFields();
        int len2 = t2.getTupleDesc().numFields();
        for (int i = 0; i < len1; ++i)
            r.setField(i, t1.getField(i));
        for (int i = 0; i < len2; ++i)
            r.setField(i+len1, t2.getField(i));
        return r;
    }

    protected Tuple readNext() throws TransactionAbortedException, DbException {
        if (t1 == null && child1.hasNext()) t1 = child1.next();
        while (true) {
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                if (jp.filter(t1, t2))
                    return join(t1, t2);
            }
            if (child1.hasNext())
                t1 = child1.next();
            else break;
            child2.rewind();
        }
        return null;
    }
}
